### ISSUE TITLE
Cannot enter the color code

### ISSUE THREAD

**Issue by tatthien** [dimitrisraptis96/copy-palette#6]
When you try to click on the Hex input, the color selector popup will close and you cannot enter the value.

However, I can input the Hex value when I try to click on the input and hold the left mouse 😂

**Comment by dimitrisraptis96** [comment]
hahaha you hacked it the finest way! However, I've fixed the annoying bug and you can enter your HEX code without hustling @tatthien  😅

**Comment by tatthien** [comment]
that's great 👍
